routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//if (env('APP_ENV') === 'production') {
//    dd('hi');
//    URL::forceSchema('https');
//}



Route::get('/', 'IndexController@index')->name('index');
//Route::get('/en', 'IndexController@index_en')->name('index_en');
//Route::get('/am', 'IndexController@index_am')->name('index_am');

Route::get('/lang_en', 'IndexController@lang_en')->name('lang_en');
Route::get('/lang_am', 'IndexController@lang_am')->name('lang_am');

Route::get('about_us', 'IndexController@about_us')->name('about_us');
Route::get('contact', 'IndexController@contact')->name('contact');
Route::get('staff', 'IndexController@staff')->name('staff');
Route::get('activity', 'IndexController@activities')->name('activities');
Route::get('volunteer', 'IndexController@volunteer')->name('volunteer');
Route::match(['GET', 'POST'],'volunteer-apply', 'IndexController@volunteerApply')->name('volunteerApply');
Route::get('donate', 'IndexController@donate')->name('donate_us');
Route::get('photo_gallery/{event?}', 'IndexController@photoGallery')->name('photo_gallery');
Route::get('volunteer-request', 'HomeController@volunteerRequest')->name('volunteerRequest');

//Route::get('c', function(){

//    $l = $request->cookies->has('lang');
//    Cookie::queue(Cookie::forget('lang'));
//    Cookie::queue(Cookie::forget('lang'));
//    Cookie::unqueue('lang');
//    Cookie::unqueue(Cookie::forever('lang'));
//    dd(Cookie::get('lang'));
//    return view('index.index');
//});

//Route::get('d', function(){
//    dd(Cookie::get('lang'));
//});

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::resource('sliderTexts', 'SliderTextController');

Route::resource('aboutuses', 'AboutUsController');

Route::resource('contacts', 'ContactController');

Route::resource('services', 'ServiceController');

Route::resource('activities', 'ActivityController');

Route::resource('events', 'EventController');

Route::resource('donates', 'DonateController');

Route::resource('photoGalleries', 'PhotoGalleryController');

Route::resource('volunteers', 'VolunteerController');

Route::resource('footers', 'FooterController');

Route::resource('users', 'UserController');

app/Models/PhotoGallery.php
<?php

namespace App\Models;

use Eloquent as Model;

/**
 * Class PhotoGallery
 * @package App\Models
 * @version July 10, 2018, 4:11 pm UTC
 *
 * @property string event_id
 * @property string image
 * @property string image_thumbnail
 * @property string who_create
 * @property string description
 * @property string type
 */
class PhotoGallery extends Model
{

    public $table = 'photo_galleries';
    


    public $fillable = [
        'event_id',
        'image',
        'image_thumbnail',
        'who_create',
        'description',
        'type'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'event_id' => 'string',
        'image' => 'string',
        'image_thumbnail' => 'string',
        'who_create' => 'string',
        'description' => 'string',
        'type' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    
}

app/Http/Controllers/PhotoGalleryController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\PhotoGalleryDataTable;
use App\Http\Requests;
use App\Http\Requests\CreatePhotoGalleryRequest;
use App\Http\Requests\UpdatePhotoGalleryRequest;
use App\Models\Event;
use App\Repositories\PhotoGalleryRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use Intervention\Image\Facades\Image;
use Response;

class PhotoGalleryController extends AppBaseController
{
    /** @var  PhotoGalleryRepository */
    private $photoGalleryRepository;

    public function __construct(PhotoGalleryRepository $photoGalleryRepo)
    {
        $this->photoGalleryRepository = $photoGalleryRepo;
    }

    /**
     * Display a listing of the PhotoGallery.
     *
     * @param PhotoGalleryDataTable $photoGalleryDataTable
     * @return Response
     */
    public function index(PhotoGalleryDataTable $photoGalleryDataTable)
    {
        $this->authorize('is-editor');

        return $photoGalleryDataTable->render('photo_galleries.index');
    }

    /**
     * Show the form for creating a new PhotoGallery.
     *
     * @return Response
     */
    public function create()
    {
        $this->authorize('is-editor');

        $events = Event::orderByDesc('created_at')->get();

        return view('photo_galleries.create', compact('events'));
    }

    /**
     * Store a newly created PhotoGallery in storage.
     *
     * @param CreatePhotoGalleryRequest $request
     *
     * @return Response
     */
    public function store(CreatePhotoGalleryRequest $request)
    {
        $this->authorize('is-editor');

        $inputs = $request->all();

        $inputs['image'] = time() . rand(1000, 9999) . $request->file('image')->getClientOriginalName();
        $path = public_path() . '/uploads/events/image/';
        $request->image->move($path, $inputs['image']);
        Image::make($path . $inputs['image'])
            ->resize('500', '300')
            ->save(public_path() . '/uploads/events/image/thumbnail/' . $inputs['image']);
        $inputs['image_thumbnail'] = $inputs['image'];
        $inputs['type'] = 1 ;
        $inputs['who_create'] = auth()->user()->id ;

        $photoGallery = $this->photoGalleryRepository->create($inputs);

        Flash::success('Photo Gallery saved successfully.');

        return redirect(route('photoGalleries.index'));
    }

    /**
     * Display the specified PhotoGallery.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $this->authorize('is-editor');

        $photoGallery = $this->photoGalleryRepository->findWithoutFail($id);

        if (empty($photoGallery)) {
            Flash::error('Photo Gallery not found');

            return redirect(route('photoGalleries.index'));
        }

        return view('photo_galleries.show')->with('photoGallery', $photoGallery);
    }

    /**
     * Show the form for editing the specified PhotoGallery.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $this->authorize('is-editor');

        $events = Event::orderByDesc('created_at')->get();

        $photoGallery = $this->photoGalleryRepository->findWithoutFail($id);

        if (empty($photoGallery)) {
            Flash::error('Photo Gallery not found');

            return redirect(route('photoGalleries.index'));
        }

        return view('photo_galleries.edit', compact('photoGallery', 'events'));
    }

    /**
     * Update the specified PhotoGallery in storage.
     *
     * @param  int              $id
     * @param UpdatePhotoGalleryRequest $request
     *
     * @return Response
     */
    public function update($id, UpdatePhotoGalleryRequest $request)
    {
        $this->authorize('is-editor');

        $photoGallery = $this->photoGalleryRepository->findWithoutFail($id);

        if (empty($photoGallery)) {
            Flash::error('Photo Gallery not found');

            return redirect(route('photoGalleries.index'));
        }

        $inputs = $request->all();
        if (isset($request->image)){
            $inputs['image'] = time() . rand(1000, 9999) . $request->file('image')->getClientOriginalName();
            $path = public_path() . '/uploads/events/image/';
            $request->image->move($path, $inputs['image']);
            Image::make($path . $inputs['image'])
                ->resize('500', '300')
                ->save(public_path() . '/uploads/events/image/thumbnail/' . $inputs['image']);
            $inputs['image_thumbnail'] = $inputs['image'];
        }
        $inputs['type'] = 1 ;
        $inputs['who_create'] = auth()->user()->id ;

        $photoGallery = $this->photoGalleryRepository->update($inputs, $id);

        Flash::success('Photo Gallery updated successfully.');

        return redirect(route('photoGalleries.index'));
    }

    /**
     * Remove the specified PhotoGallery from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $this->authorize('is-editor');

        $photoGallery = $this->photoGalleryRepository->findWithoutFail($id);

        if (empty($photoGallery)) {
            Flash::error('Photo Gallery not found');

            return redirect(route('photoGalleries.index'));
        }

        $this->photoGalleryRepository->delete($id);

        Flash::success('Photo Gallery deleted successfully.');

        return redirect(route('photoGalleries.index'));
    }
}

resources/views/photo_galleries/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Photo Gallery
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'photoGalleries.store','files' => true]) !!}

                        @include('photo_galleries.fields')

                    {!! Form::close() !!}
                </div>
            </div>

        </div>
    </div>
@endsection

resources/views/photo_galleries/datatables_actions.blade.php
{!! Form::open(['route' => ['photoGalleries.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('photoGalleries.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
    <a href="{{ route('photoGalleries.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-edit"></i>
    </a>
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/photo_galleries/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Photo Gallery
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($photoGallery, ['route' => ['photoGalleries.update', $photoGallery->id], 'method' => 'patch','files' => true]) !!}

                        @include('photo_galleries.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/photo_galleries/fields.blade.php
<!-- Event Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('event_id', 'Event Name:') !!}
    {{--{!! Form::text('event_id', null, ['class' => 'form-control']) !!}--}}
    <select name="event_id" id="event_id" class="form-control">
        @foreach($events as $event)
            <option value="{{$event->id}}">{{$event->name}}</option>
        @endforeach
    </select>
</div>

<div class="form-group col-sm-6">
    {!! Form::label('description', 'Description:') !!}
    {!! Form::text('description', null, ['class' => 'form-control']) !!}
</div>

<!-- Image Field -->
<div class="form-group col-sm-6">
    {!! Form::label('image', 'Image:') !!}
    {!! Form::file('image', null, ['class' => 'form-control']) !!}
</div>

<!-- Image Thumbnail Field -->
{{--<div class="form-group col-sm-6">--}}
    {{--{!! Form::label('image_thumbnail', 'Image Thumbnail:') !!}--}}
    {!! Form::hidden('image_thumbnail', null, ['class' => 'form-control']) !!}
{{--</div>--}}

<!-- Who Create Field -->
{{--<div class="form-group col-sm-6">--}}
    {{--{!! Form::label('who_create', 'Who Create:') !!}--}}
    {!! Form::hidden('who_create', null, ['class' => 'form-control']) !!}
{{--</div>--}}

<!-- Description Field -->

<!-- Type Field -->
{{--<div class="form-group col-sm-6">--}}
    {{--{!! Form::label('type', 'Type:') !!}--}}
    {!! Form::hidden('type', null, ['class' => 'form-control']) !!}
{{--</div>--}}

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('photoGalleries.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/photo_galleries/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Photo Galleries</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('photoGalleries.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('photo_galleries.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/photo_galleries/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Photo Gallery
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('photo_galleries.show_fields')
                    <a href="{!! route('photoGalleries.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/photo_galleries/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $photoGallery->id !!}</p>
</div>

<!-- Event Id Field -->
<div class="form-group">
    {!! Form::label('event_id', 'Event Id:') !!}
    <p>{!! $photoGallery->event_id !!}</p>
</div>

<!-- Image Field -->
<div class="form-group">
    {!! Form::label('image', 'Image:') !!}
    <p>{!! $photoGallery->image !!}</p>
</div>

<!-- Image Thumbnail Field -->
<div class="form-group">
    {!! Form::label('image_thumbnail', 'Image Thumbnail:') !!}
    <p>{!! $photoGallery->image_thumbnail !!}</p>
</div>

<!-- Who Create Field -->
<div class="form-group">
    {!! Form::label('who_create', 'Who Create:') !!}
    <p>{!! $photoGallery->who_create !!}</p>
</div>

<!-- Description Field -->
<div class="form-group">
    {!! Form::label('description', 'Description:') !!}
    <p>{!! $photoGallery->description !!}</p>
</div>

<!-- Type Field -->
<div class="form-group">
    {!! Form::label('type', 'Type:') !!}
    <p>{!! $photoGallery->type !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $photoGallery->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $photoGallery->updated_at !!}</p>
</div>

resources/views/photo_galleries/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%']) !!}

@section('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endsection