routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//if (env('APP_ENV') === 'production') {
//    dd('hi');
//    URL::forceSchema('https');
//}



Route::get('/', 'IndexController@index')->name('index');
//Route::get('/en', 'IndexController@index_en')->name('index_en');
//Route::get('/am', 'IndexController@index_am')->name('index_am');

Route::get('/lang_en', 'IndexController@lang_en')->name('lang_en');
Route::get('/lang_am', 'IndexController@lang_am')->name('lang_am');

Route::get('about_us', 'IndexController@about_us')->name('about_us');
Route::get('contact', 'IndexController@contact')->name('contact');
Route::get('staff', 'IndexController@staff')->name('staff');
Route::get('activity', 'IndexController@activities')->name('activities');
Route::get('volunteer', 'IndexController@volunteer')->name('volunteer');
Route::match(['GET', 'POST'],'volunteer-apply', 'IndexController@volunteerApply')->name('volunteerApply');
Route::get('donate', 'IndexController@donate')->name('donate_us');
Route::get('photo_gallery/{event?}', 'IndexController@photoGallery')->name('photo_gallery');
Route::get('volunteer-request', 'HomeController@volunteerRequest')->name('volunteerRequest');

//Route::get('c', function(){

//    $l = $request->cookies->has('lang');
//    Cookie::queue(Cookie::forget('lang'));
//    Cookie::queue(Cookie::forget('lang'));
//    Cookie::unqueue('lang');
//    Cookie::unqueue(Cookie::forever('lang'));
//    dd(Cookie::get('lang'));
//    return view('index.index');
//});

//Route::get('d', function(){
//    dd(Cookie::get('lang'));
//});

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::resource('sliderTexts', 'SliderTextController');

Route::resource('aboutuses', 'AboutUsController');

Route::resource('contacts', 'ContactController');

Route::resource('services', 'ServiceController');

Route::resource('activities', 'ActivityController');

Route::resource('events', 'EventController');

Route::resource('donates', 'DonateController');

Route::resource('photoGalleries', 'PhotoGalleryController');

Route::resource('volunteers', 'VolunteerController');

Route::resource('footers', 'FooterController');

Route::resource('users', 'UserController');

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'role_id',
        'password',
        'first_name',
        'last_name',
        'birthday',
        'mobile',
        'gender',
        'image',
        'country',
        'address',
        'profession',
        'age',
        'about_me',
        'start_activity',
        'end_activity',
        'first_name',
        'gender',
        'upload',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use Intervention\Image\Facades\Image;
use Laracasts\Flash\Flash;

class UserController extends Controller
{
    public function index()//ok
    {
        $this->authorize('is-admin');
        $users = User::orderByDesc('created_at')->paginate(10);

        return view('users.index', compact('users'));
    }

    public function create()//ok
    {
        $this->authorize('is-admin');

        return view('users.create');
    }

    public function store(Request $request)
    {
        $this->authorize('is-admin');

        $inputs = $request->all();

        if (isset($request->image)){
            $inputs['image'] = time() . rand(1000, 9999) . $request->file('image')->getClientOriginalName();
            $path = public_path() . '/uploads/users/image/';
            $request->image->move($path, $inputs['image']);
            Image::make($path . $inputs['image'])
                ->resize('500', '350')
                ->save(public_path() . '/uploads/users/image/thumbnail/' . $inputs['image']);
        }

        User::create($inputs);

        Flash::success('User saved successfully.');

        return redirect(route('users.index'));
    }

    public function show($id)//doesn't work
    {
        $this->authorize('is-admin');

        $sliderText = $this->sliderTextRepository->findWithoutFail($id);

        if (empty($sliderText)) {
            Flash::error('User Text not found');

            return redirect(route('sliderTexts.index'));
        }

        return view('slider_texts.show')->with('sliderText', $sliderText);
    }

    public function edit(User $user)//ok
    {
        $this->authorize('is-admin');

        if (empty($user)) {
            Flash::error('User not found');

            return redirect(route('users.index'));
        }

        return view('users.edit', compact('user'));
    }

    public function update(User $user, Request $request)
    {
        $this->authorize('is-admin');

        if (empty($user)) {
            Flash::error('User not found');

            return redirect(route('users.index'));
        }

        $inputs = $request->all();

        if (isset($request->image)){
            $inputs['image'] = time() . rand(1000, 9999) . $request->file('image')->getClientOriginalName();
            $path = public_path() . '/uploads/users/image/';
            $request->image->move($path, $inputs['image']);
            Image::make($path . $inputs['image'])
                ->resize('500', '350')
                ->save(public_path() . '/uploads/users/image/thumbnail/' . $inputs['image']);
        }

        $user->update($inputs);

        Flash::success('User updated successfully.');

        return redirect(route('users.index'));
    }

    public function destroy(User $user)//ok
    {
        $this->authorize('is-admin');

        if (empty($user)) {
            Flash::error('User not found');

            return redirect(route('users.index'));
        }

        $user->delete();

        Flash::success('User deleted successfully.');

        return redirect(route('users.index'));
    }
}

resources/views/users/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            user
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'users.store','files' => true]) !!}

                        @include('users.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/users/datatables_actions.blade.php
{!! Form::open(['route' => ['events.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('events.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
    <a href="{{ route('events.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-edit"></i>
    </a>
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            User
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($user, ['route' => ['users.update', $user->id], 'method' => 'patch', 'files' => true]) !!}

                        @include('users.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/users/fields.blade.php
<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'name:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>
<div class="form-group col-sm-6">
    {!! Form::label('last_name', 'last name:') !!}
    {!! Form::text('last_name', null, ['class' => 'form-control']) !!}
</div>
<div class="form-group col-sm-6">
    {!! Form::label('email', 'email:') !!}
    {!! Form::text('email', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group col-sm-6">
    {!! Form::label('first_name', 'real email:') !!}
    {!! Form::text('first_name', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group col-sm-6">
    {!! Form::label('role_id', 'role:') !!}
    <select name="role_id" class="form-control" id="">
        <option value="1" @if((isset($user))&&($user->role_id == 1)) selected @endif >Normal user</option>
        <option value="0" @if((isset($user))&&($user->role_id == 0)) selected @endif >Rejected volunteer</option>
        <option value="2" @if((isset($user))&&($user->role_id == 2)) selected @endif >Requested volunteer</option>
        <option value="3" @if((isset($user))&&($user->role_id == 3)) selected @endif >volunteer</option>
        <option value="4" @if((isset($user))&&($user->role_id == 4)) selected @endif >Editor</option>
        <option value="5" @if((isset($user))&&($user->role_id == 5)) selected @endif >Manager</option>
    </select>
</div>

<div class="form-group col-sm-6">
    {!! Form::label('image', 'image:') !!}
    {!! Form::file('image', ['class' => 'form-control']) !!}
</div>

@if(isset($user->image))
    <div class="form-group col-sm-6">
        {!! Form::label('now_image', 'uploaded image:') !!}
        <img width="100%" src="{{route('index')}}/uploads/users/image/{{$user->image}}">
    </div>
@endif

<div class="form-group col-sm-6">
    {!! Form::label('country', 'country:') !!}
    {!! Form::text('country', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group col-sm-6">
    {!! Form::label('address', 'address:') !!}
    {!! Form::text('address', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group col-sm-6">
    {!! Form::label('profession', 'profession:') !!}
    {!! Form::text('profession', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group col-sm-6">
    {!! Form::label('age', 'facebook:') !!}
    {!! Form::text('age', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group col-sm-6">
    {!! Form::label('mobile', 'mobile:') !!}
    {!! Form::text('mobile', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group col-sm-6">
    {!! Form::label('about_me', 'about me:') !!}
    {!! Form::text('about_me', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group col-sm-6">
    {!! Form::label('start_activity', 'start volunteer date:(you can leave empty)') !!}
    {!! Form::text('start_activity', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group col-sm-6">
    {!! Form::label('end_activity', 'end volunteer activity:(you can leave empty)') !!}
    {!! Form::text('end_activity', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group col-sm-6">
    {!! Form::label('birthday', 'birthday:') !!}
    <select name="birthday" id="" class="form-control">
        @for($i = 0; $i <120; $i++  )
        <option value="{{$i+1900}}" @if((isset($user)) && ($user->birthday == $i+1900) ) selected @endif >{{$i+1900}}</option>
        @endfor
    </select>
</div>

<div class="form-group col-sm-6">
    {!! Form::label('gender', 'gender:') !!}
    <select name="gender" class="form-control" id="">
        <option value="male" @if((isset($user))&&($user->gender == 'male')) selected @endif >male</option>
        <option value="female" @if((isset($user))&&($user->gender == 'female')) selected @endif >female</option>
        <option value="other" @if((isset($user))&&($user->gender == 'other')) selected @endif >other</option>
    </select>
</div>



@if((isset($user)) && (isset($user->upload)))
    <div class="form-group col-sm-6">
        <div>
            <a href="{{route('index')}}/{{$user->upload}}">Click here to download CV</a>
        </div>
    </div>
@endif

{{--<div class="form-group col-sm-6">--}}
    {{--{!! Form::label('birthday', 'birthday:') !!}--}}
    {{--{!! Form::text('birthday', null, ['class' => 'form-control']) !!}--}}
{{--</div>--}}

{{--<div class="form-group col-sm-6">--}}
    {{--{!! Form::label('birthday', 'birthday:') !!}--}}
    {{--{!! Form::text('birthday', null, ['class' => 'form-control']) !!}--}}
{{--</div>--}}


{{--<div class="form-group col-sm-6">--}}
    {{--{!! Form::label('time', 'Time:') !!}--}}
    {{--<div id="picker"></div>--}}
    {{--<input type="hidden" id="result" value="2017-01-01 00:00" name="time">--}}
{{--</div>--}}

<!-- Image Field -->
{{--<div class="form-group col-sm-6">--}}
    {{--{!! Form::label('image', 'Image:') !!}--}}
    {{--{!! Form::file('image', null, ['class' => 'form-control']) !!}--}}
{{--</div>--}}


<!-- Image Thumbnail Field -->
{{--<div class="form-group col-sm-6">--}}
{{--    {!! Form::label('image_thumbnail', 'Image Thumbnail:') !!}--}}
{{--    {!! Form::hidden('image_thumbnail', null, ['class' => 'form-control']) !!}--}}
{{--</div>--}}

<!-- Time Field -->



<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('events.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/users/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Users</h1>
        <h1 class="pull-right">
            <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px"
               href="{!! route('users.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">

                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>Email</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($users as $user)
                        <tr  style="background-color:
                        @if($user->role_id == 0) rgba(255,0,0,0.5) @endif
                        @if($user->role_id == 1) rgba(255,242,247,0.57) @endif
                        @if($user->role_id == 2) rgba(255,212,26,0.57) @endif
                        @if($user->role_id == 3) rgba(92,255,99,0.57) @endif
                        @if($user->role_id == 4) rgba(87,99,255,0.57) @endif
                        @if($user->role_id == 5) rgba(0,35,255,0.57) @endif

                                "  >
                            <td>{{$user->email}}</td>
                            <td>
                                {!! Form::open(['route'=>['users.destroy', $user->id ], 'method' => 'delete' ]) !!}
                                <table>
                                    <tr>
                                        <td>
                                            <div class="btn-group">
                                                {{--<a href="{{ route('users.show', $user->id) }}"--}}
                                                   {{--class='btn btn-default btn-xs'>--}}
                                                    {{--<i class="glyphicon glyphicon-eye-open"></i>--}}
                                                {{--</a>--}}
                                                <a href="{{ route('users.edit', $user->id) }}"
                                                   class='btn btn-default btn-xs'>
                                                    <i class="glyphicon glyphicon-edit"></i>
                                                </a>
                                                {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
                                                        'type' => 'submit',
                                                        'class' => 'btn btn-danger btn-xs',
                                                        'onclick' => "return confirm('Are you sure?')"
                                                    ]) !!}
                                            </div>
                                        </td>
                                    </tr>
                                </table>
                                {!! Form::close() !!}
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>

                {{$users->links()}}

            </div>


        </div>
        <span style="background-color: rgba(255,242,247,0.57)">normal user</span><br>
        <span style="background-color: rgba(255,0,0,0.5)">rejected volunteer</span><br>
        <span style="background-color: rgba(255,212,26,0.57)">requested volunteer</span><br>
        <span style="background-color: rgba(92,255,99,0.57)">accepted volunteer</span><br>
        <span style="background-color: rgba(87,99,255,0.57)">editor</span><br>
        <span style="background-color: rgba(0,35,255,0.57)">manager</span><br>

        <div class="text-center">

        </div>
    </div>
@endsection

resources/views/users/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Event
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('events.show_fields')
                    <a href="{!! route('events.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/users/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $event->id !!}</p>
</div>

<!-- Name Field -->
<div class="form-group">
    {!! Form::label('name', 'Name:') !!}
    <p>{!! $event->name !!}</p>
</div>

<!-- Image Field -->
<div class="form-group">
    {!! Form::label('image', 'Image:') !!}
    <p>{!! $event->image !!}</p>
</div>

<!-- Image Thumbnail Field -->
<div class="form-group">
    {!! Form::label('image_thumbnail', 'Image Thumbnail:') !!}
    <p>{!! $event->image_thumbnail !!}</p>
</div>

<!-- Time Field -->
<div class="form-group">
    {!! Form::label('time', 'Time:') !!}
    <p>{!! $event->time !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $event->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $event->updated_at !!}</p>
</div>

resources/views/users/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%']) !!}

@section('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endsection