routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//if (env('APP_ENV') === 'production') {
//    dd('hi');
//    URL::forceSchema('https');
//}



Route::get('/', 'IndexController@index')->name('index');
//Route::get('/en', 'IndexController@index_en')->name('index_en');
//Route::get('/am', 'IndexController@index_am')->name('index_am');

Route::get('/lang_en', 'IndexController@lang_en')->name('lang_en');
Route::get('/lang_am', 'IndexController@lang_am')->name('lang_am');

Route::get('about_us', 'IndexController@about_us')->name('about_us');
Route::get('contact', 'IndexController@contact')->name('contact');
Route::get('staff', 'IndexController@staff')->name('staff');
Route::get('activity', 'IndexController@activities')->name('activities');
Route::get('volunteer', 'IndexController@volunteer')->name('volunteer');
Route::match(['GET', 'POST'],'volunteer-apply', 'IndexController@volunteerApply')->name('volunteerApply');
Route::get('donate', 'IndexController@donate')->name('donate_us');
Route::get('photo_gallery/{event?}', 'IndexController@photoGallery')->name('photo_gallery');
Route::get('volunteer-request', 'HomeController@volunteerRequest')->name('volunteerRequest');

//Route::get('c', function(){

//    $l = $request->cookies->has('lang');
//    Cookie::queue(Cookie::forget('lang'));
//    Cookie::queue(Cookie::forget('lang'));
//    Cookie::unqueue('lang');
//    Cookie::unqueue(Cookie::forever('lang'));
//    dd(Cookie::get('lang'));
//    return view('index.index');
//});

//Route::get('d', function(){
//    dd(Cookie::get('lang'));
//});

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::resource('sliderTexts', 'SliderTextController');

Route::resource('aboutuses', 'AboutUsController');

Route::resource('contacts', 'ContactController');

Route::resource('services', 'ServiceController');

Route::resource('activities', 'ActivityController');

Route::resource('events', 'EventController');

Route::resource('donates', 'DonateController');

Route::resource('photoGalleries', 'PhotoGalleryController');

Route::resource('volunteers', 'VolunteerController');

Route::resource('footers', 'FooterController');

Route::resource('users', 'UserController');

app/Models/SliderText.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class SliderText
 * @package App\Models
 * @version June 30, 2018, 8:23 pm UTC
 *
 * @property string big_text
 * @property string small_text
 * @property string big_text_am
 * @property string small_text_am
 */
class SliderText extends Model
{
//    use SoftDeletes;

    public $table = 'slider_texts';
    

//    protected $dates = ['deleted_at'];


    public $fillable = [
        'big_text',
        'small_text',
        'big_text_am',
        'small_text_am'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'big_text' => 'string',
        'small_text' => 'string',
        'big_text_am' => 'string',
        'small_text_am' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    
}

app/Http/Controllers/SliderTextController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\SliderTextDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateSliderTextRequest;
use App\Http\Requests\UpdateSliderTextRequest;
use App\Repositories\SliderTextRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use Response;

class SliderTextController extends AppBaseController
{
    /** @var  SliderTextRepository */
    private $sliderTextRepository;

    public function __construct(SliderTextRepository $sliderTextRepo)
    {
        $this->sliderTextRepository = $sliderTextRepo;
    }

    /**
     * Display a listing of the SliderText.
     *
     * @param SliderTextDataTable $sliderTextDataTable
     * @return Response
     */
    public function index(SliderTextDataTable $sliderTextDataTable)
    {
        $this->authorize('is-admin');

        return $sliderTextDataTable->render('slider_texts.index');
    }

    /**
     * Show the form for creating a new SliderText.
     *
     * @return Response
     */
    public function create()
    {
        $this->authorize('is-admin');

        return view('slider_texts.create');
    }

    /**
     * Store a newly created SliderText in storage.
     *
     * @param CreateSliderTextRequest $request
     *
     * @return Response
     */
    public function store(CreateSliderTextRequest $request)
    {
        $this->authorize('is-admin');

        $input = $request->all();

        $sliderText = $this->sliderTextRepository->create($input);

        Flash::success('Slider Text saved successfully.');

        return redirect(route('sliderTexts.index'));
    }

    /**
     * Display the specified SliderText.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $this->authorize('is-admin');

        $sliderText = $this->sliderTextRepository->findWithoutFail($id);

        if (empty($sliderText)) {
            Flash::error('Slider Text not found');

            return redirect(route('sliderTexts.index'));
        }

        return view('slider_texts.show')->with('sliderText', $sliderText);
    }

    /**
     * Show the form for editing the specified SliderText.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $this->authorize('is-admin');

        $sliderText = $this->sliderTextRepository->findWithoutFail($id);

        if (empty($sliderText)) {
            Flash::error('Slider Text not found');

            return redirect(route('sliderTexts.index'));
        }

        return view('slider_texts.edit')->with('sliderText', $sliderText);
    }

    /**
     * Update the specified SliderText in storage.
     *
     * @param  int              $id
     * @param UpdateSliderTextRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateSliderTextRequest $request)
    {
        $this->authorize('is-admin');

        $sliderText = $this->sliderTextRepository->findWithoutFail($id);

        if (empty($sliderText)) {
            Flash::error('Slider Text not found');

            return redirect(route('sliderTexts.index'));
        }

        $sliderText = $this->sliderTextRepository->update($request->all(), $id);

        Flash::success('Slider Text updated successfully.');

        return redirect(route('sliderTexts.index'));
    }

    /**
     * Remove the specified SliderText from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $this->authorize('is-admin');

        $sliderText = $this->sliderTextRepository->findWithoutFail($id);

        if (empty($sliderText)) {
            Flash::error('Slider Text not found');

            return redirect(route('sliderTexts.index'));
        }

        $this->sliderTextRepository->delete($id);

        Flash::success('Slider Text deleted successfully.');

        return redirect(route('sliderTexts.index'));
    }
}

resources/views/slider_texts/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Slider Text
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'sliderTexts.store']) !!}

                        @include('slider_texts.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/slider_texts/datatables_actions.blade.php
{!! Form::open(['route' => ['sliderTexts.destroy', $id], 'method' => 'delete']) !!}
{!! Form::open(['route' => ['sliderTexts.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('sliderTexts.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
    <a href="{{ route('sliderTexts.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-edit"></i>
    </a>
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/slider_texts/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Slider Text
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($sliderText, ['route' => ['sliderTexts.update', $sliderText->id], 'method' => 'patch']) !!}

                        @include('slider_texts.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/slider_texts/fields.blade.php
<!-- Big Text Field -->
<div class="form-group col-sm-6">
    {!! Form::label('big_text', 'Big Text:') !!}
    {!! Form::text('big_text', null, ['class' => 'form-control']) !!}
</div>

<!-- Small Text Field -->
<div class="form-group col-sm-6">
    {!! Form::label('small_text', 'Small Text:') !!}
    {!! Form::text('small_text', null, ['class' => 'form-control']) !!}
</div>

<!-- Big Text Am Field -->
<div class="form-group col-sm-6">
    {!! Form::label('big_text_am', 'Big Text Am:') !!}
    {!! Form::text('big_text_am', null, ['class' => 'form-control']) !!}
</div>

<!-- Small Text Am Field -->
<div class="form-group col-sm-6">
    {!! Form::label('small_text_am', 'Small Text Am:') !!}
    {!! Form::text('small_text_am', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('sliderTexts.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/slider_texts/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Slider Texts</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('sliderTexts.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('slider_texts.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/slider_texts/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Slider Text
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('slider_texts.show_fields')
                    <a href="{!! route('sliderTexts.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/slider_texts/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $sliderText->id !!}</p>
</div>

<!-- Big Text Field -->
<div class="form-group">
    {!! Form::label('big_text', 'Big Text:') !!}
    <p>{!! $sliderText->big_text !!}</p>
</div>

<!-- Small Text Field -->
<div class="form-group">
    {!! Form::label('small_text', 'Small Text:') !!}
    <p>{!! $sliderText->small_text !!}</p>
</div>

<!-- Big Text Am Field -->
<div class="form-group">
    {!! Form::label('big_text_am', 'Big Text Am:') !!}
    <p>{!! $sliderText->big_text_am !!}</p>
</div>

<!-- Small Text Am Field -->
<div class="form-group">
    {!! Form::label('small_text_am', 'Small Text Am:') !!}
    <p>{!! $sliderText->small_text_am !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $sliderText->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $sliderText->updated_at !!}</p>
</div>

resources/views/slider_texts/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%']) !!}

@section('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endsection