routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//if (env('APP_ENV') === 'production') {
//    dd('hi');
//    URL::forceSchema('https');
//}



Route::get('/', 'IndexController@index')->name('index');
//Route::get('/en', 'IndexController@index_en')->name('index_en');
//Route::get('/am', 'IndexController@index_am')->name('index_am');

Route::get('/lang_en', 'IndexController@lang_en')->name('lang_en');
Route::get('/lang_am', 'IndexController@lang_am')->name('lang_am');

Route::get('about_us', 'IndexController@about_us')->name('about_us');
Route::get('contact', 'IndexController@contact')->name('contact');
Route::get('staff', 'IndexController@staff')->name('staff');
Route::get('activity', 'IndexController@activities')->name('activities');
Route::get('volunteer', 'IndexController@volunteer')->name('volunteer');
Route::match(['GET', 'POST'],'volunteer-apply', 'IndexController@volunteerApply')->name('volunteerApply');
Route::get('donate', 'IndexController@donate')->name('donate_us');
Route::get('photo_gallery/{event?}', 'IndexController@photoGallery')->name('photo_gallery');
Route::get('volunteer-request', 'HomeController@volunteerRequest')->name('volunteerRequest');

//Route::get('c', function(){

//    $l = $request->cookies->has('lang');
//    Cookie::queue(Cookie::forget('lang'));
//    Cookie::queue(Cookie::forget('lang'));
//    Cookie::unqueue('lang');
//    Cookie::unqueue(Cookie::forever('lang'));
//    dd(Cookie::get('lang'));
//    return view('index.index');
//});

//Route::get('d', function(){
//    dd(Cookie::get('lang'));
//});

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::resource('sliderTexts', 'SliderTextController');

Route::resource('aboutuses', 'AboutUsController');

Route::resource('contacts', 'ContactController');

Route::resource('services', 'ServiceController');

Route::resource('activities', 'ActivityController');

Route::resource('events', 'EventController');

Route::resource('donates', 'DonateController');

Route::resource('photoGalleries', 'PhotoGalleryController');

Route::resource('volunteers', 'VolunteerController');

Route::resource('footers', 'FooterController');

Route::resource('users', 'UserController');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Admin panel</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>

    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">

    <!-- Theme style -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.4.3/css/AdminLTE.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.4.3/css/skins/_all-skins.min.css">

    <!-- iCheck -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/iCheck/1.0.2/skins/square/_all.css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/css/select2.min.css">

    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">

    <link rel="stylesheet" href="{{asset('Datetime-Picker-jQuery-Moment/css/datetimepicker.css')}}">

    @yield('css')
</head>

<body class="skin-blue sidebar-mini">
@if (!Auth::guest())
    <div class="wrapper">
        <!-- Main Header -->
        <header class="main-header">

            <!-- Logo -->
            <a href="#" class="logo">
                <b>InfyOm</b>
            </a>

            <!-- Header Navbar -->
            <nav class="navbar navbar-static-top" role="navigation">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>
                <!-- Navbar Right Menu -->
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <!-- User Account Menu -->
                        <li class="dropdown user user-menu">
                            <!-- Menu Toggle Button -->
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <!-- The user image in the navbar-->
                                <img src="http://infyom.com/images/logo/blue_logo_150x150.jpg"
                                     class="user-image" alt="User Image"/>
                                <!-- hidden-xs hides the username on small devices so only the image appears. -->
                                <span class="hidden-xs">{!! Auth::user()->name !!}</span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- The user image in the menu -->
                                <li class="user-header">
                                    <img src="http://infyom.com/images/logo/blue_logo_150x150.jpg"
                                         class="img-circle" alt="User Image"/>
                                    <p>
                                        {!! Auth::user()->name !!}
                                        <small>Member since {!! Auth::user()->created_at->format('M. Y') !!}</small>
                                    </p>
                                </li>
                                <!-- Menu Footer-->
                                <li class="user-footer">
                                    <div class="pull-left">
                                        <a href="#" class="btn btn-default btn-flat">Profile</a>
                                    </div>
                                    <div class="pull-right">
                                        <a href="{!! url('/logout') !!}" class="btn btn-default btn-flat"
                                           onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                            Sign out
                                        </a>
                                        <form id="logout-form" action="{{ url('/logout') }}" method="POST"
                                              style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>

        <!-- Left side column. contains the logo and sidebar -->
    @include('layouts.sidebar')
    <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            @yield('content')
        </div>

        <!-- Main Footer -->
        <footer class="main-footer" style="max-height: 100px;text-align: center">
            <strong>Copyright © 2018 <a href="#">Company</a>.</strong> All rights reserved.
        </footer>

    </div>
@else
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#app-navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Branding Image -->
                <a class="navbar-brand" href="{!! url('/') !!}">
                    InfyOm Generator
                </a>
            </div>

            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <!-- Left Side Of Navbar -->
                <ul class="nav navbar-nav">
                    <li><a href="{!! url('/home') !!}">Home</a></li>
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    <li><a href="{!! url('/login') !!}">Login</a></li>
                    <li><a href="{!! url('/register') !!}">Register</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div id="page-content-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    @yield('content')
                </div>
            </div>
        </div>
    </div>
@endif

<!-- jQuery 3.1.1 -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<!-- AdminLTE App -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.4.3/js/adminlte.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/iCheck/1.0.2/icheck.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/js/select2.min.js"></script>

<script src="{{asset('tinymce/js/tinymce/tinymce.min.js')}}"></script>
<script>tinymce.init({selector: 'textarea'});</script>

<script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha384-nvAa0+6Qg9clwYCGGPpDQLVpLNn0fRaROjHqs13t4Ggj3Ez50XnGQqc/r8MhnRDZ" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.0/moment-with-locales.min.js"></script>
<script src="{{asset('Datetime-Picker-jQuery-Moment/js/datetimepicker.js')}}"></script>
<script>
    $('#picker').dateTimePicker({
        selectData: "now",
        dateFormat: "YYYY-MM-DD HH:mm",
        showTime: true,
        locale: 'en',
        positionShift: { top: 20, left: 0},
        title: "Select Date and Time",
        buttonTitle: "Select"
    });
</script>

<!-- AdminLTE App toggle-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.3.3/js/app.min.js"></script>

@yield('scripts')
</body>
</html>

resources/views/layouts/datatables_css.blade.php
<!-- DataTable Bootstrap -->
<link href="https://cdn.datatables.net/1.10.12/css/dataTables.bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="//cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.2.2/css/buttons.bootstrap.min.css">

resources/views/layouts/datatables_js.blade.php
<!-- Datatables -->
<script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.12/js/dataTables.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.colVis.min.js"></script>
<script src="{{ asset('vendor/datatables/buttons.server-side.js') }}"></script>

resources/views/layouts/index.blade.php
<!DOCTYPE html>
<html lang="EN">
<head>

    <title>Patmosararat</title>
    <!--meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script>
        addEventListener("load", function () {
            setTimeout(hideURLbar, 0);
        }, false);

        function hideURLbar() {
            window.scrollTo(0, 1);
        }
    </script>
    <!--//meta tags ends here-->
    <!--booststrap-->
    <link href="{{asset('css/bootstrap.css')}}" rel="stylesheet" type="text/css" media="all">
    <!--//booststrap end-->
    <!-- font-awesome icons -->
    <link href="{{asset('css/font-awesome.css')}}" rel="stylesheet">
    <!-- //font-awesome icons -->
    <link rel="stylesheet" href="{{asset('css/owl.carousel.css')}}" type="text/css" media="all">
    <!-- clients-->
    <!--stylesheets-->
    <link href="{{asset('css/style.css')}}" rel='stylesheet' type='text/css' media="all">
    <!--//stylesheets-->
    <link href="//fonts.googleapis.com/css?family=Montserrat:300,400,500" rel="stylesheet">


</head>

@yield('header')

@stack('header')

<body>

@yield('content')


@yield('scripts')
@stack('scripts')

<!--footer-->
<!--js working-->
<script src='{{asset('js/jquery-2.2.3.min.js')}}'></script>
<!-- //js  working-->
<script src="{{asset('js/responsiveslides.min.js')}}"></script>
<script>
    // You can also use "$(window).load(function() {"
    $(function () {
        // Slideshow 4
        $("#slider4").responsiveSlides({
            auto: true,
            pager: false,
            nav: true,
            speed: 900,
            namespace: "callbacks",
            before: function () {
                $('.events').append("<li>before event fired.</li>");
            },
            after: function () {
                $('.events').append("<li>after event fired.</li>");
            }
        });

    });
</script>
<!--// banner-->
<!--client carousel -->
<script src="{{asset('js/owl.carousel.js')}}"></script>
<script>
    $(document).ready(function () {
        $("#owl-demo").owlCarousel({
            items: 1,
            itemsDesktop: [768, 1],
            itemsDesktopSmall: [414, 1],
            lazyLoad: true,
            autoPlay: true,
            navigation: true,

            navigationText: false,
            pagination: true,

        });

    });
</script>
<!-- start-smoth-scrolling -->
<script  src="{{asset('js/move-top.js')}}"></script>
<script  src="{{asset('js/easing.js')}}"></script>
<script >
    jQuery(document).ready(function ($) {
        $(".scroll").click(function (event) {
            event.preventDefault();
            $('html,body').animate({ scrollTop: $(this.hash).offset().top }, 1000);
        });
    });
</script>
<!-- start-smoth-scrolling -->
<!-- here stars scrolling icon -->
<script>
    $(document).ready(function () {
        /*
            var defaults = {
            containerID: 'toTop', // fading element id
            containerHoverID: 'toTopHover', // fading element hover id
            scrollSpeed: 1200,
            easingType: 'linear'
            };
        */

        $().UItoTop({ easingType: 'easeOutQuart' });

    });
</script>
<!-- //here ends scrolling icon -->
<!--bootstrap working-->
<script src="{{asset('js/bootstrap.js')}}"></script>
<!-- //bootstrap working-->

</body>
</html>

resources/views/layouts/menu.blade.php
<li>
    <a href="{!! route('index') !!}"><i class="fa fa-desktop"></i><span>Website</span></a>
</li>
<li class="{{ Request::is('home') ? 'active' : '' }}">
    <a href="{!! route('index') !!}/home"><i class="fa fa-home"></i><span>Home</span></a>
</li>
<hr style="border-color: #2c3b41">
@can('is-admin')
<li class="{{ Request::is('sliderTexts*') ? 'active' : '' }}">
    <a href="{!! route('sliderTexts.index') !!}"><i class="fa fa-edit"></i><span>Slider Texts</span></a>
</li>

<li class="{{ Request::is('aboutuses*') ? 'active' : '' }}">
    <a href="{!! route('aboutuses.index') !!}"><i class="fa fa-edit"></i><span>About us Text</span></a>
</li>

<li class="{{ Request::is('contacts*') ? 'active' : '' }}">
    <a href="{!! route('contacts.index') !!}"><i class="fa fa-edit"></i><span>Contact us Text</span></a>
</li>

{{--<li class="{{ Request::is('services*') ? 'active' : '' }}">--}}
    {{--<a href="{!! route('services.index') !!}"><i class="fa fa-edit"></i><span>Services</span></a>--}}
{{--</li>--}}

<li class="{{ Request::is('activities*') ? 'active' : '' }}">
    <a href="{!! route('activities.index') !!}"><i class="fa fa-edit"></i><span>Activities Text</span></a>
</li>

<li class="{{ Request::is('donates*') ? 'active' : '' }}">
    <a href="{!! route('donates.index') !!}"><i class="fa fa-edit"></i><span>Donates Text</span></a>
</li>

<li class="{{ Request::is('volunteers*') ? 'active' : '' }}">
    <a href="{!! route('volunteers.index') !!}"><i class="fa fa-edit"></i><span>Volunteer Text</span></a>
</li>

<li class="{{ Request::is('footers*') ? 'active' : '' }}">
    <a href="{!! route('footers.index') !!}"><i class="fa fa-edit"></i><span>Footers Text</span></a>
</li>

<hr style="border-color: #2c3b41">

<li class="{{ Request::is('users*') ? 'active' : '' }}">
    <a href="{!! route('users.index') !!}"><i class="fa fa-user"></i><span>Users</span></a>
</li>

@endcan

<hr style="border-color: #2c3b41">

@can('is-editor')
<li class="{{ Request::is('events*') ? 'active' : '' }}">
    <a href="{!! route('events.index') !!}"><i class="fa fa-calendar"></i><span>Events</span></a>
</li>

<li class="{{ Request::is('photoGalleries*') ? 'active' : '' }}">
    <a href="{!! route('photoGalleries.index') !!}"><i class="fa fa-camera"></i><span>Photo Galleries</span></a>
</li>
@endcan

resources/views/layouts/sidebar.blade.php
<aside class="main-sidebar" id="sidebar-wrapper">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

        <!-- Sidebar user panel (optional) -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="http://infyom.com/images/logo/blue_logo_150x150.jpg" class="img-circle"
                     alt="User Image"/>
            </div>
            <div class="pull-left info">
                @if (Auth::guest())
                <p>InfyOm</p>
                @else
                    <p>{{ Auth::user()->name}}</p>
                @endif
                <!-- Status -->
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>

        <!-- search form (Optional) -->
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search..."/>
          <span class="input-group-btn">
            <button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i>
            </button>
          </span>
            </div>
        </form>
        <!-- Sidebar Menu -->

        <ul class="sidebar-menu" data-widget="tree">
            @include('layouts.menu')
        </ul>
        <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
</aside>